name: 1 - Provisioning Backend Infrastructure

on:
    workflow_dispatch:

jobs:
  backend-infrastructure:
    name: Productions Backend Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Print
        run: echo "Provisioning Backend Infrastructure"
