name: 1 - Provisioning Backend Infrastructure

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write
  security-events: write
  actions: read
  checks: write
  issues: write

jobs:
  backend-infrastructure:
    name: Backend Infrastructure
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AW_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: ${{ secrets.AWS_STS }}
          role-session-name: GitHubActions-${{github.run_id}}

      - name: Terraform Format Check
        uses: dflook/terraform-fmt-check@v1
        with:
          path: terraform/backend-infra

      - name: Provision Backend Infrastructure Initial Setup
        working-directory: terraform/backend-infra
        run: terraform init -input=false -no-color

      - name: Provision Backend Infrastructure Plan
        working-directory: terraform/backend-infra
        run: terraform plan -out=tfplan

      - name: Provision Provision Backend Infrastructure Apply
        working-directory: terraform/backend-infra
        run: terraform apply -auto-approve
